package com.yang.counter.persist.entity;

import java.util.Date;

public class UrlInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_info.id
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_info.title
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_info.url
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_info.char_num
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    private Integer charNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_info.chinese_number
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    private Integer chineseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_info.mark_num
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    private Integer markNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_info.total_num
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    private Integer totalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_info.create_time
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_info.id
     *
     * @return the value of url_info.id
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_info.id
     *
     * @param id the value for url_info.id
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_info.title
     *
     * @return the value of url_info.title
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_info.title
     *
     * @param title the value for url_info.title
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_info.url
     *
     * @return the value of url_info.url
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_info.url
     *
     * @param url the value for url_info.url
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_info.char_num
     *
     * @return the value of url_info.char_num
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public Integer getCharNum() {
        return charNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_info.char_num
     *
     * @param charNum the value for url_info.char_num
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public void setCharNum(Integer charNum) {
        this.charNum = charNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_info.chinese_number
     *
     * @return the value of url_info.chinese_number
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public Integer getChineseNumber() {
        return chineseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_info.chinese_number
     *
     * @param chineseNumber the value for url_info.chinese_number
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public void setChineseNumber(Integer chineseNumber) {
        this.chineseNumber = chineseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_info.mark_num
     *
     * @return the value of url_info.mark_num
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public Integer getMarkNum() {
        return markNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_info.mark_num
     *
     * @param markNum the value for url_info.mark_num
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public void setMarkNum(Integer markNum) {
        this.markNum = markNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_info.total_num
     *
     * @return the value of url_info.total_num
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_info.total_num
     *
     * @param totalNum the value for url_info.total_num
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_info.create_time
     *
     * @return the value of url_info.create_time
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_info.create_time
     *
     * @param createTime the value for url_info.create_time
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}