package com.yang.counter.persist.mapper;

import com.yang.counter.persist.entity.UrlInfo;
import com.yang.counter.persist.entity.UrlInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrlInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    long countByExample(UrlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    int deleteByExample(UrlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    int insert(UrlInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    int insertSelective(UrlInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    List<UrlInfo> selectByExample(UrlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    UrlInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") UrlInfo record, @Param("example") UrlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    int updateByExample(@Param("record") UrlInfo record, @Param("example") UrlInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    int updateByPrimaryKeySelective(UrlInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_info
     *
     *   Mon Jun 18 00:03:17 CST 2018
     */
    int updateByPrimaryKey(UrlInfo record);
}